"""Embedded store master lookup baked from LOOKUPS.xlsx (STORE sheet).

Note that S121 'Fun Republic' appears twice in the source file (Super & Hyper).
We keep the first occurrence (Super); admins can edit/add via the UI.
"""

DEFAULT_STORES = [
    {'Store Code': 'D070', 'Store Name': 'Springdale S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D087', 'Store Name': 'Lake Town S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D089', 'Store Name': 'DGP Bidhana S', 'Region': 'East', 'City': 'Durgapur', 'Cluster': 'DGP', 'Format': 'Daily'},
    {'Store Code': 'D104', 'Store Name': 'Asansol S', 'Region': 'East', 'City': 'Asansole', 'Cluster': 'DGP', 'Format': 'Daily'},
    {'Store Code': 'D166', 'Store Name': 'B T Road S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D202', 'Store Name': 'Tolly Club S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D263', 'Store Name': 'LKO Rajendra Nagar S', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Daily'},
    {'Store Code': 'D265', 'Store Name': 'LKO Aliganj Chandralok S', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Daily'},
    {'Store Code': 'D266', 'Store Name': 'LKO Rajajipuram S', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Daily'},
    {'Store Code': 'D269', 'Store Name': 'LKO Vikas Nagar S', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Daily'},
    {'Store Code': 'D270', 'Store Name': 'LKO Vivek Khand S', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Daily'},
    {'Store Code': 'D278', 'Store Name': 'LKO Ashiana S', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Daily'},
    {'Store Code': 'D333', 'Store Name': 'LKO Janakipuram S', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Daily'},
    {'Store Code': 'D345', 'Store Name': 'LKO Indira Nagar Sec12 S', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Daily'},
    {'Store Code': 'D346', 'Store Name': 'Varanasi Mahmoorganj S', 'Region': 'East UP', 'City': 'Varanasi', 'Cluster': 'Varanasi', 'Format': 'Daily'},
    {'Store Code': 'D354', 'Store Name': 'Ramrajatala S', 'Region': 'East', 'City': 'Howrah', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D357', 'Store Name': 'LKO Eldeco S', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Daily'},
    {'Store Code': 'D359', 'Store Name': 'Kol AMP Baisakhi S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D360', 'Store Name': 'LKO Aliganj Odhani S', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Daily'},
    {'Store Code': 'D362', 'Store Name': 'LKO Vikas Nagar Sec2 S', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Daily'},
    {'Store Code': 'D365', 'Store Name': 'Kol Rajarhat Siddha S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D371', 'Store Name': 'KOL Purti Aqua S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D374', 'Store Name': 'KOL Azadgarh S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D375', 'Store Name': 'KOL Raynagar S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D378', 'Store Name': 'KOL Madhyamgram S', 'Region': 'East', 'City': 'Madhyamgram', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D379', 'Store Name': 'Kol Aurobinda Mall S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D386', 'Store Name': 'LKO Vrindavan Colony S', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Daily'},
    {'Store Code': 'D388', 'Store Name': 'Konnagar S', 'Region': 'East', 'City': 'Konnagar', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D390', 'Store Name': 'Gorakhpur Taramandal S', 'Region': 'East UP', 'City': 'Gorakhpur', 'Cluster': 'Gorakhpur', 'Format': 'Daily'},
    {'Store Code': 'D391', 'Store Name': 'KOL Mukundapur S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D394', 'Store Name': 'Varanasi PDR Mall S', 'Region': 'East UP', 'City': 'Varanasi', 'Cluster': 'Varanasi', 'Format': 'Daily'},
    {'Store Code': 'D400', 'Store Name': 'KOL Sodepur S', 'Region': 'East', 'City': 'Sodepur', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D410', 'Store Name': 'KOL Alipore S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'D418', 'Store Name': 'Siliguri Sevoke Road S', 'Region': 'East', 'City': 'Siliguri', 'Cluster': 'Siliguri', 'Format': 'Daily'},
    {'Store Code': 'H009', 'Store Name': 'Mani Square', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Hyper'},
    {'Store Code': 'H012', 'Store Name': 'South City', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Hyper'},
    {'Store Code': 'H013', 'Store Name': 'Rashbehari', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Hyper'},
    {'Store Code': 'S121', 'Store Name': 'Fun Republic', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Super'},
    {'Store Code': 'H030', 'Store Name': 'Gorakhpur', 'Region': 'East UP', 'City': 'Gorakhpur', 'Cluster': 'Gorakhpur', 'Format': 'Hyper'},
    {'Store Code': 'H042', 'Store Name': 'Siliguri', 'Region': 'East', 'City': 'Siliguri', 'Cluster': 'Siliguri', 'Format': 'Hyper'},
    {'Store Code': 'H048', 'Store Name': 'Lekhraj', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Hyper'},
    {'Store Code': 'H049', 'Store Name': 'Axis Mall', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Hyper'},
    {'Store Code': 'H069', 'Store Name': 'New Town Square', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Hyper'},
    {'Store Code': 'H072', 'Store Name': 'Quest', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Hyper'},
    {'Store Code': 'H081', 'Store Name': 'B T Road', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Hyper'},
    {'Store Code': 'H090', 'Store Name': 'Durgapur', 'Region': 'East', 'City': 'Durgapur', 'Cluster': 'DGP', 'Format': 'Hyper'},
    {'Store Code': 'H100', 'Store Name': 'Belur', 'Region': 'East', 'City': 'Howrah', 'Cluster': 'Kolkata', 'Format': 'Hyper'},
    {'Store Code': 'H104', 'Store Name': 'Madhyamgram', 'Region': 'East', 'City': 'Madhyamgram', 'Cluster': 'Kolkata', 'Format': 'Hyper'},
    {'Store Code': 'H115', 'Store Name': 'Sodepur Meena Icon', 'Region': 'East', 'City': 'Sodepur', 'Cluster': 'Kolkata', 'Format': 'Hyper'},
    {'Store Code': 'H126', 'Store Name': 'Metro Crystal Square', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Hyper'},
    {'Store Code': 'H129', 'Store Name': 'Crown Mall', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Hyper'},
    {'Store Code': 'H139', 'Store Name': 'Liluah', 'Region': 'East', 'City': 'Howrah', 'Cluster': 'Kolkata', 'Format': 'Hyper'},
    {'Store Code': 'H143', 'Store Name': 'Varanasi Pahariya', 'Region': 'East UP', 'City': 'Varanasi', 'Cluster': 'Varanasi', 'Format': 'Hyper'},
    {'Store Code': 'S004', 'Store Name': 'Avisar', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'S040', 'Store Name': 'Allahabad', 'Region': 'East UP', 'City': 'Allahabad', 'Cluster': 'Varanasi', 'Format': 'Super'},
    {'Store Code': 'S041', 'Store Name': 'Upohar', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'S046', 'Store Name': 'Rajarhat DLF', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'S053', 'Store Name': 'Varanasi Bhelupur', 'Region': 'East UP', 'City': 'Varanasi', 'Cluster': 'Varanasi', 'Format': 'Super'},
    {'Store Code': 'S055', 'Store Name': 'Gorakhpur Padri Bazar', 'Region': 'East UP', 'City': 'Gorakhpur', 'Cluster': 'Gorakhpur', 'Format': 'Super'},
    {'Store Code': 'S056', 'Store Name': 'Siliguri Vega', 'Region': 'East', 'City': 'Siliguri', 'Cluster': 'Siliguri', 'Format': 'Super'},
    {'Store Code': 'S059', 'Store Name': 'Acropolis Mall', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'S060', 'Store Name': 'Unitech', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'S062', 'Store Name': 'Barrackpore', 'Region': 'East', 'City': 'Barrackpore', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'S064', 'Store Name': 'Kharagpur', 'Region': 'East', 'City': 'Kharagpur', 'Cluster': 'DGP', 'Format': 'Super'},
    {'Store Code': 'S065', 'Store Name': 'Maheshtala', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'S066', 'Store Name': 'Barasat', 'Region': 'East', 'City': 'Barasat', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'S070', 'Store Name': 'Gariahat', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'S077', 'Store Name': 'Haldia', 'Region': 'East', 'City': 'Haldia', 'Cluster': 'DGP', 'Format': 'Super'},
    {'Store Code': 'S080', 'Store Name': 'Purulia', 'Region': 'East', 'City': 'Purulia', 'Cluster': 'DGP', 'Format': 'Super'},
    {'Store Code': 'S083', 'Store Name': 'Vrindavan', 'Region': 'East UP', 'City': 'Vrindavan', 'Cluster': 'Lucknow', 'Format': 'Super'},
    {'Store Code': 'S085', 'Store Name': 'Serampore Super', 'Region': 'East', 'City': 'Sreerampore', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'S088', 'Store Name': 'Varanasi Senpura', 'Region': 'East UP', 'City': 'Varanasi', 'Cluster': 'Varanasi', 'Format': 'Super'},
    {'Store Code': 'S089', 'Store Name': 'Varanasi Sigra', 'Region': 'East UP', 'City': 'Varanasi', 'Cluster': 'Varanasi', 'Format': 'Super'},
    {'Store Code': 'S090', 'Store Name': 'Laketown', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'S091', 'Store Name': 'AD Mall', 'Region': 'East UP', 'City': 'Gorakhpur', 'Cluster': 'Gorakhpur', 'Format': 'Super'},
    {'Store Code': 'S095', 'Store Name': 'DGP Benachity', 'Region': 'East', 'City': 'Durgapur', 'Cluster': 'DGP', 'Format': 'Super'},
    {'Store Code': 'S100', 'Store Name': 'KOL Hazra Super', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'S110', 'Store Name': 'Bhojubeer', 'Region': 'East UP', 'City': 'Varanasi', 'Cluster': 'Varanasi', 'Format': 'Super'},
    {'Store Code': 'S113', 'Store Name': 'Bhadohi', 'Region': 'East UP', 'City': 'Bhadhoi', 'Cluster': 'Varanasi', 'Format': 'Super'},
    {'Store Code': 'S117', 'Store Name': 'Spencers Wholesale Bazaar', 'Region': 'East', 'City': 'Siliguri', 'Cluster': 'Siliguri', 'Format': 'Super'},
    {'Store Code': 'V010', 'Store Name': 'Baroda', 'Region': 'Baroda', 'City': 'Baroda', 'Cluster': 'Baroda', 'Format': 'Daily'},
    {'Store Code': 'X011', 'Store Name': 'Mahamayatala S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'X015', 'Store Name': 'Tolly Heights S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'X017', 'Store Name': 'Garia S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'X019', 'Store Name': 'Patauli S', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Daily'},
    {'Store Code': 'S106', 'Store Name': 'Barabanki Super', 'Region': 'East UP', 'City': 'Barbanki', 'Cluster': 'Lucknow', 'Format': 'Super'},
    {'Store Code': 'S119', 'Store Name': 'Siliguri Burdwan Road', 'Region': 'East', 'City': 'Siliguri', 'Cluster': 'Siliguri', 'Format': 'Super'},
    {'Store Code': 'S120', 'Store Name': 'Narendrapur Sucasa', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'H029', 'Store Name': 'Fun Republic', 'Region': 'East UP', 'City': 'Lucknow', 'Cluster': 'Lucknow', 'Format': 'Hyper'},
    {'Store Code': 'S111', 'Store Name': 'KOL Merlin One', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Super'},
    {'Store Code': 'M053', 'Store Name': 'Rpsg Cafeteria', 'Region': 'East', 'City': 'Kolkata', 'Cluster': 'Kolkata', 'Format': 'Super'},
]
